namespace HareDu.Diagnostics.Model;

/// <summary>
/// Represents a summary of analysis results performed by an analyzer, including the categorized states of Healthy, Unhealthy, Warning, and Inconclusive.
/// </summary>
public record AnalyzerSummary
{
    /// <summary>
    /// Gets the unique identifier associated with an analyzer summary.
    /// </summary>
    public string Id { get; init; }

    /// <summary>
    /// Gets the diagnostic results that represent healthy components within the analyzer summary.
    /// </summary>
    public AnalyzerResult Healthy { get; init; }

    /// <summary>
    /// Represents the result of components that have been analyzed and determined to be in an unhealthy state.
    /// </summary>
    public AnalyzerResult Unhealthy { get; init; }

    /// <summary>
    /// Represents the summarized results of warning diagnostics generated by the analyzer,
    /// including the total count and percentage of warning instances.
    /// </summary>
    public AnalyzerResult Warning { get; init; }

    /// <summary>
    /// Represents the details of inconclusive analysis results, including relevant metrics and statistics.
    /// </summary>
    public AnalyzerResult Inconclusive { get; init; }
}