namespace HareDu.Diagnostics.Model;

using System;
using System.Collections.Generic;

/// <summary>
/// Represents the context of an analyzer, containing relevant information
/// about the analysis performed, including a unique identifier, a collection
/// of analysis summaries, and a timestamp indicating when the analysis occurred.
/// </summary>
public record AnalyzerContext
{
    /// <summary>
    /// Represents the unique identifier associated with the context of an analyzer.
    /// This property is typically used to distinguish between different analyzer contexts,
    /// enabling traceability and correlation of analysis processes.
    /// </summary>
    public Guid Id { get; init; }

    /// <summary>
    /// Represents a collection of analysis summaries generated by the analyzer, providing insights
    /// into various aspects of the diagnostic results, categorized into key states such as Healthy,
    /// Unhealthy, Warning, and Inconclusive.
    /// </summary>
    public IReadOnlyList<AnalyzerSummary> Summary { get; init; }

    /// <summary>
    /// Represents the timestamp indicating when the associated analysis context was created or recorded.
    /// This property is used to track the temporal context of analysis operations or events.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; }
}